name: ncwu_plugin
version: '${project.version}'
main: com.chank.NcwuPlugin
api-version: '1.20'

commands:
  menu:
    description: "自定义菜单相关"
    aliases: mu
  myplugin:
    description: "华水测试插件"
    #    permission: MyPlugin.Main
    aliases: mp
  tpa:
    description: "发送传送请求到其他玩家"
  tpaccept:
    description: "接受传送请求"